projectName=Momento Worker
projectGroup=com.momentoworker

sourceCompatibility=21
targetCompatibility=21

org.gradle.jvmargs=-Djava.awt.headless=true -Xms512m -Xmx2048m -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.warning.mode=all

gradleVersion=8.0

# build system dependencies
gradleOsackyDoctor=0.9.2

systemProp.testlogger.slowThreshold=5000
systemProp.testlogger.showStandardStreams=false

springBootVersion=3.2.4
springDependencyManagementVersion=1.1.4
springCloudVersion=2023.0.1
springdocVersion=2.6.0
jwtVersion=0.12.5
mapstructVersion=1.6.2
awsSdkVersion=2.25.31
thumbnailatorVersion=0.4.20
